from pypluto import pluto
import time
#A sample program to test the drone API
drone1=pluto(DroneIP="192.168.4.1")
drone1.connect()
drone1.disarm()
# drone1.arm()
time.sleep(2)
print("taking off")
drone1.takeoff()
time.sleep(2)
print("adding throttle")
drone1.throttle_speed(0)
time.sleep(15)
print("landing")
# time.sleep(10)
# drone1.change_val()
# drone1.disarm()
# time.sleep(2)
# drone1.arm()
# time.sleep(2)
# drone1.disarm()
#drone.keyboard_control()